version: 3
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    base: "master" # Specify the base branch
    head: "master"
    open-pull-requests-limit: 10
