name: Deployment on container
on:
  push:

jobs:
  build-on-docker:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci

      - name: Install Trivy
        run: |
         wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
         tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
         sudo mv trivy /usr/local/bin

      - name: Build Docker Image
        run: docker build -t faizul56/npmtest .

      - name: Security Scan with Trivy
        run: |
          trivy --format json --output /tmp/trivy_report.json faizul56/npmtest

      - name: Download Trivy Report
        run: |
          mkdir -p ${{ github.workspace }}/reports
          mv /tmp/trivy_report.json ${{ github.workspace }}/reports/

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: ${{ github.workspace }}/reports/trivy_report.json


      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}


