name: Deployment on container
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-on-docker:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci

      - name: Install Trivy
        run: |
         wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
         tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
         sudo mv trivy /usr/local/bin

      - name: Build Docker Image
        run: docker build -t faizul56/npmtest .

      #- name: Security Scan with Trivy
      #  run: |
      #   trivy --format json --output /tmp/trivy_report.json faizul56/npmtest

      #- name: Download Trivy Report
       # run: |
        #  mkdir -p ${{ github.workspace }}/reports
         # mv /tmp/trivy_report.json ${{ github.workspace }}/reports/

      #- name: Upload Trivy Report
       # uses: actions/upload-artifact@v2
        #with:
         # name: trivy-report
          #path: ${{ github.workspace }}/reports/trivy_report.json



      - name: Run Docker Container
        run: |
          docker run --rm -d -p 8080:80 --name npmtest-container faizul56/npmtest


      - name: Set up Bash Environment
        run: echo "export GITHUB_TOKEN=\${{ secrets.MY_GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Grant Execute Permissions
        run: chmod +x deployment_count.sh

      
      - name: Execute Bash Script
        run: ./deployment_count.sh


      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Capture Deployment Frequency
        id: deployment_frequency
        run: |
          DEPLOYMENT_COUNT=$(./deployment_count.sh)
          echo "Deployment Count: $DEPLOYMENT_COUNT"
          echo "::set-output name=deployment_count::$DEPLOYMENT_COUNT"
          mkdir -p deployment-frequency
          echo $DEPLOYMENT_COUNT > deployment-frequency/deployment_count.txt


      - name: Upload Deployment Frequency
        uses: actions/upload-artifact@v2
        with:
          name: deployment-frequency
          path: deployment-frequency
  


      

      
      - name: Download Previous Deployment Frequency
        uses: actions/download-artifact@v2
        with:
          name: deployment-frequency
          path: deployment-frequency

      - name: Append Deployment Count
        run: |
          PREVIOUS_COUNT=$(cat deployment-frequency/deployment_count.txt || echo 0)
          NEW_COUNT=$((PREVIOUS_COUNT + DEPLOYMENT_COUNT))
          echo "$NEW_COUNT" > deployment-frequency/deployment_count.txt


      - name: Upload Deployment Frequency
        uses: actions/upload-artifact@v2
        with:
          name: deployment-frequency
          path: deployment-frequency


 

      
      
      
