name: Deployment on container
on:
  push:

jobs:
  build-on-docker:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci

      - name: Install Trivy
        run: |
         wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.17.2_Linux-64bit.tar.gz
         tar zxvf trivy_0.17.2_Linux-64bit.tar.gz
         sudo mv trivy /usr/local/bin

      - name: Build Docker Image
        run: docker build -t faizul56/npmtest .

      - name: Security Scan with Trivy
        run: |
          trivy --format json --output /tmp/trivy_report.json faizul56/npmtest


